const financialAffirmations= [
    "Hoy atraigo abundancia y prosperidad a mi vida.",
    "Soy un imán para el dinero y las oportunidades financieras.",
    "Mis ingresos aumentan constantemente.",
    "Manejo mi dinero con sabiduría y responsabilidad.",
    "Cada día tomo decisiones financieras que me acercan a mis metas.",
    "El dinero fluye hacia mí de fuentes esperadas e inesperadas.",
    "Estoy abierto/a a recibir riqueza en todas sus formas.",
    "Mis inversiones crecen y me brindan seguridad.",
    "Soy agradecido/a por la abundancia que ya tengo en mi vida.",
    "Visualizo un futuro financiero brillante y lo manifiesto con mis acciones.",
    "Soy merecedor/a de la libertad financiera.",
    "La abundancia es mi estado natural.",
    "Transformo mis creencias limitantes sobre el dinero en creencias de prosperidad.",
    "Aprendo continuamente sobre finanzas y mejoro mi inteligencia financiera.",
    "Mis acciones hoy siembran las semillas de mi éxito financiero futuro.",
    "Disfruto del proceso de construir mi riqueza.",
    "El universo conspira a mi favor para mi bienestar financiero.",
    "Soy capaz de superar cualquier desafío financiero con confianza y creatividad.",
    "Mi trabajo y mis talentos son valiosos y bien recompensados.",
    "Cada gasto es una oportunidad para tomar una decisión consciente sobre mi dinero.",
    "Estoy en paz con mi situación financiera actual y confío en mi capacidad para mejorarla.",
    "Mi mente está enfocada en la creación de valor y la generación de ingresos.",
    "Atraigo clientes y oportunidades que contribuyen a mi crecimiento financiero.",
    "Soy un excelente administrador/a de mis recursos.",
    "Mi relación con el dinero es positiva, sana y poderosa.",
    "Mi potencial para generar ingresos es ilimitado.",
    "Cada inversión que hago trabaja inteligentemente para mí.",
    "Soy un solucionador/a de problemas financieros creativo/a.",
    "El dinero es una herramienta poderosa que utilizo para el bien.",
    "Estoy construyendo una base financiera sólida y duradera.",
    "Mis ahorros crecen de forma constante y segura.",
    "Atraigo mentores y guías financieros sabios.",
    "Veo oportunidades financieras donde otros ven obstáculos.",
    "Mi confianza en mis decisiones financieras aumenta cada día.",
    "Estoy aprendiendo a hacer que mi dinero trabaje para mí.",
    "Soy consciente de mis gastos y los alineo con mis valores.",
    "Honro el dinero y lo trato con respeto.",
    "Estoy creando múltiples fuentes de ingresos.",
    "Mi mentalidad de abundancia atrae más abundancia.",
    "Libero cualquier resistencia al flujo de dinero en mi vida.",
    "Soy un imán para la riqueza y la prosperidad sostenibles.",
    "Mis ingresos superan mis gastos con facilidad.",
    "Estoy en control de mi futuro financiero.",
    "Cada paso que doy me acerca más a mi libertad financiera.",
    "Celebro mis éxitos financieros, grandes y pequeños.",
    "Utilizo mi dinero para crear experiencias enriquecedoras.",
    "Soy un ejemplo de éxito financiero para otros.",
    "Mi intuición me guía hacia decisiones financieras acertadas.",
    "Estoy creando un legado financiero positivo.",
    "El dinero apoya mis propósitos y pasiones.",
    "Soy un inversionista inteligente y perspicaz.",
    "Mi planificación financiera me brinda tranquilidad.",
    "Estoy expandiendo mi capacidad para recibir grandes sumas de dinero.",
    "El universo siempre me provee de lo que necesito y más.",
    "Soy resiliente ante los desafíos financieros temporales.",
    "Mi valor aumenta y se refleja en mis ingresos.",
    "Estoy creando un colchón financiero seguro.",
    "Atraigo soluciones financieras innovadoras.",
    "Mi relación con el dinero está basada en la confianza y la seguridad.",
    "Estoy construyendo activos que generan ingresos pasivos.",
    "Soy un estudiante constante del mundo financiero.",
    "Mi energía positiva atrae oportunidades lucrativas.",
    "Estoy alineado/a con la energía de la prosperidad.",
    "El dinero es una herramienta para crear más valor en el mundo.",
    "Soy un administrador/a eficiente de mis deudas.",
    "Mi camino hacia la abundancia es claro y fácil.",
    "Estoy creando un futuro financiero lleno de posibilidades.",
    "Mis talentos y habilidades son altamente valorados financieramente.",
    "Soy un creador/a activo/a de mi propia riqueza.",
    "El dinero fluye hacia mí de manera constante y armoniosa.",
    "Estoy aprendiendo a disfrutar de la abundancia en mi vida.",
    "Mis metas financieras se manifiestan fácilmente.",
    "Soy un pensador/a estratégico/a en temas de dinero.",
    "Mi confianza financiera crece exponencialmente.",
    "Estoy construyendo una red de contactos financieros exitosos."
  ];
  
  export default financialAffirmations

  console.log(financialAffirmations.length);